# Generated by Django 4.1.4 on 2023-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_time_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=400)),
                ('file', models.ImageField(upload_to='faculty_images')),
            ],
        ),
    ]
