# Generated by Django 4.1.4 on 2023-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='file',
            field=models.ImageField(upload_to='faculty_images/'),
        ),
    ]
