# Generated by Django 4.1.4 on 2023-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_coding_events_hackathons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_cell_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=300)),
                ('file', models.ImageField(upload_to='research_cell_faculty_images/')),
            ],
        ),
    ]
