# Generated by Django 4.1.4 on 2023-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_paper_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_cell_faculty',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
