# Generated by Django 4.1.4 on 2023-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_research_cell_faculty_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.TextField(max_length=500)),
                ('batch', models.IntegerField(max_length=15)),
                ('banner', models.ImageField(upload_to='alumni_students_images/')),
            ],
        ),
    ]
