# Generated by Django 4.1.4 on 2023-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_alumni_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.CharField(max_length=15),
        ),
    ]
